-- MySQL Script generated by MySQL Workbench
-- Wed Dec 17 08:17:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema camodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `camodb` ;

-- -----------------------------------------------------
-- Schema camodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camodb` DEFAULT CHARACTER SET utf8mb4 ;
USE `camodb` ;

-- -----------------------------------------------------
-- Table `camodb`.`NPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`NPC` (
  `idNPC` INT NOT NULL AUTO_INCREMENT,
  `nameFirst` VARCHAR(45) NOT NULL,
  `nameLast` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NOT NULL,
  `gender` ENUM('male', 'female', 'non-binary') NOT NULL,
  PRIMARY KEY (`idNPC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`storylet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`storylet` (
  `idStorylet` INT NOT NULL AUTO_INCREMENT,
  `idNPC` INT NOT NULL,
  `nameStorylet` VARCHAR(45) NOT NULL,
  `contentStorylet` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idStorylet`),
  UNIQUE INDEX `uniq_npc_storylet` (`idNPC` ASC, `nameStorylet` ASC) VISIBLE,
  INDEX `idNPC` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_storylet_npc`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `nameFirst` VARCHAR(45) NULL DEFAULT NULL,
  `nameLast` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`completedStorylet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`completedStorylet` (
  `idStorylet` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idStorylet`, `idUser`),
  INDEX `fk_completed_storylet_user` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_completed_storylet_storylet`
    FOREIGN KEY (`idStorylet`)
    REFERENCES `camodb`.`storylet` (`idStorylet`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_completed_storylet_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`tasks` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `taskName` VARCHAR(45) NOT NULL,
  `taskDetails` TEXT NOT NULL,
  `idNPC` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_tasks_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `camodb`.`user_task`
-- -----------------------------------------------------
CREATE TABLE user_task (
  idUser INT NOT NULL,
  idTask INT NOT NULL,
  status ENUM('active','completed','failed') NOT NULL DEFAULT 'active',
  startedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt DATETIME NULL,
  PRIMARY KEY (idUser, idTask),
  CONSTRAINT fk_user_task_user
    FOREIGN KEY (idUser) REFERENCES user(idUser)
    ON DELETE CASCADE,
  CONSTRAINT fk_user_task_task
    FOREIGN KEY (idTask) REFERENCES tasks(idTask)
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Table `camodb`.`relationshipType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`relationshipType` (
  `idRelationshipType` INT NOT NULL AUTO_INCREMENT,
  `typeRelationship` ENUM('friend', 'stranger', 'enemy', 'acquaintance', 'mentor', 'family') NOT NULL,
  `descriptionRelationship` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idRelationshipType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `camodb`.`playerNPCrelationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`playerNPCrelationship` (
  `idUser` INT NOT NULL,
  `idNPC` INT NOT NULL,
  `trust` FLOAT NOT NULL DEFAULT 30,
  `wasEnemy` TINYINT(1) NOT NULL DEFAULT 0,

  PRIMARY KEY (`idUser`, `idNPC`),

  INDEX `idx_playerNPC_idNPC` (`idNPC` ASC) VISIBLE,

  CONSTRAINT `fk_rel_npc`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_rel_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION

) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`precondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`precondition` (
  `idPrecondition` INT NOT NULL AUTO_INCREMENT,
  `idNPC` INT NOT NULL,
  `nameCondition` VARCHAR(64) NOT NULL,
  `conditionDescription` TEXT NOT NULL,
  PRIMARY KEY (`idPrecondition`),
  INDEX `fk_precondition_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_precondition_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`choice` (
  `idChoice` INT NOT NULL AUTO_INCREMENT,
  `idSourceStorylet` INT NOT NULL,
  `choiceText` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idChoice`),
  INDEX `fk_choice_storylet1_idx` (`idSourceStorylet` ASC) VISIBLE,
  CONSTRAINT `fk_choice_storylet1`
    FOREIGN KEY (`idSourceStorylet`)
    REFERENCES `camodb`.`storylet` (`idStorylet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NULL DEFAULT NULL,
  `itemType` VARCHAR(45) NULL DEFAULT NULL,
  `itemDescription` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`userItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`userItem` (
  `idUser` INT NOT NULL,
  `iditem` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_userItem_user1_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`iditem`, `idUser`),
  CONSTRAINT `fk_userItem_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userItem_item1`
    FOREIGN KEY (`iditem`)
    REFERENCES `camodb`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`NPCItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`NPCItem` (
  `iditem` INT NOT NULL,
  `idNPC` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`iditem`, `idNPC`),
  INDEX `fk_NPCItem_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_NPCItem_item1`
    FOREIGN KEY (`iditem`)
    REFERENCES `camodb`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NPCItem_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npc_user_memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npc_user_memory` (
  `idNPC` INT NOT NULL,
  `idUser` INT NOT NULL,
  `kbText` LONGTEXT NULL DEFAULT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idNPC`, `idUser`),
  INDEX `fk_KB_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_KB_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KB_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`background`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`background` (
  `idNPC` INT NOT NULL,
  `BGcontent` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idNPC`),
  INDEX `fk_background_NPC1_idx` (`idNPC` ASC) VISIBLE,
  CONSTRAINT `fk_background_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`storylet_preconditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`storylet_preconditions` (
  `idPrecondition` INT NOT NULL,
  `idStorylet` INT NOT NULL,
  PRIMARY KEY (`idPrecondition`, `idStorylet`),
  INDEX `fk_preconditions_storylet1_idx` (`idStorylet` ASC) VISIBLE,
  CONSTRAINT `fk_preconditions_precondition1`
    FOREIGN KEY (`idPrecondition`)
    REFERENCES `camodb`.`precondition` (`idPrecondition`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconditions_storylet1`
    FOREIGN KEY (`idStorylet`)
    REFERENCES `camodb`.`storylet` (`idStorylet`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`emotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`emotion` (
  `idEmotion` INT NOT NULL AUTO_INCREMENT,
  `emotion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmotion`),
  UNIQUE INDEX `emotion_UNIQUE` (`emotion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`userEmotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`userEmotion` (
  `idUser` INT NOT NULL,
  `idEmotion` INT NOT NULL,
  `emotionIntensity` FLOAT NOT NULL,
  INDEX `fk_userEmotion_user1_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`idEmotion`, `idUser`),
  CONSTRAINT `fk_userEmotion_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userEmotion_emotion1`
    FOREIGN KEY (`idEmotion`)
    REFERENCES `camodb`.`emotion` (`idEmotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npcEmotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npcEmotion` (
  `idNPC` INT NOT NULL,
  `idEmotion` INT NOT NULL,
  `emotionIntensity` FLOAT NOT NULL,
  PRIMARY KEY (`idNPC`, `idEmotion`),
  INDEX `fk_npcEmotion_emotion1_idx` (`idEmotion` ASC) VISIBLE,
  CONSTRAINT `fk_npcEmotion_NPC1`
    FOREIGN KEY (`idNPC`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_npcEmotion_emotion1`
    FOREIGN KEY (`idEmotion`)
    REFERENCES `camodb`.`emotion` (`idEmotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`npcNPCrelationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npcNPCrelationship` (
  `idNPC_1` INT NOT NULL,
  `idNPC_2` INT NOT NULL,
  `trust` FLOAT NOT NULL DEFAULT 50,
  `wasEnemy` TINYINT(1) NOT NULL DEFAULT 0,

  PRIMARY KEY (`idNPC_1`, `idNPC_2`),

  INDEX `idx_npcNPC_idNPC1` (`idNPC_1` ASC) VISIBLE,
  INDEX `idx_npcNPC_idNPC2` (`idNPC_2` ASC) VISIBLE,

  CONSTRAINT `fk_npcNPCrelationship_NPC1`
    FOREIGN KEY (`idNPC_1`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_npcNPCrelationship_NPC2`
    FOREIGN KEY (`idNPC_2`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION

) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `camodb`.`npc_npc_memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`npc_npc_memory` (
  `idNPC_1` INT NOT NULL,
  `idNPC_2` INT NOT NULL,
  `kbText` LONGTEXT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`idNPC_1`, `idNPC_2`),
  INDEX `fk_npc_npc_memory_NPC2_idx` (`idNPC_2` ASC) VISIBLE,
  CONSTRAINT `fk_npc_npc_memory_NPC1`
    FOREIGN KEY (`idNPC_1`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_npc_npc_memory_NPC2`
    FOREIGN KEY (`idNPC_2`)
    REFERENCES `camodb`.`NPC` (`idNPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camodb`.`user_precondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camodb`.`user_precondition` (
  `idUser` INT NOT NULL,
  `idPrecondition` INT NOT NULL,
  `conditionMet` TINYINT(1) NOT NULL DEFAULT 0,
  `updatedAt` DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`, `idPrecondition`),
  INDEX `fk_user_precondition_precondition1_idx` (`idPrecondition` ASC) VISIBLE,
  CONSTRAINT `fk_user_precondition_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `camodb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_precondition_precondition1`
    FOREIGN KEY (`idPrecondition`)
    REFERENCES `camodb`.`precondition` (`idPrecondition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `camodb`.`npc_persona`
-- -----------------------------------------------------
CREATE TABLE npc_persona (
  idNPC INT NOT NULL,
  role VARCHAR(64) NOT NULL,
  personality_traits TEXT NOT NULL,
  emotional_tendencies TEXT NOT NULL,
  emotion_decay_rate FLOAT DEFAULT 0.9,
  emotion_reactivity FLOAT DEFAULT 1.0,
  speech_style TEXT NULL,
  moral_alignment TEXT NULL,
  PRIMARY KEY (idNPC),
  CONSTRAINT fk_npc_persona_npc
    FOREIGN KEY (idNPC)
    REFERENCES NPC(idNPC)
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Table `camodb`.`npc_user_belief`
-- -----------------------------------------------------
DROP TABLE IF EXISTS npc_user_belief;

CREATE TABLE npc_user_belief (
  idNPC INT NOT NULL,
  idUser INT NOT NULL,

  beliefType ENUM(
    'current_emotion',
    'moral_alignment',
    'age',
    'gender',
    'life_story',
    'personality_trait',
    'secret',
    'goal'
  ) NOT NULL,

  beliefValue VARCHAR(255) NOT NULL,

  beliefSource ENUM(
    'dialogue',
    'task',
    'emotion_analysis',
    'third_party',
    'inference'
  ) DEFAULT 'dialogue',

  confidence FLOAT NOT NULL DEFAULT 0.5,

  evidence TEXT NULL,

  updatedAt DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (idNPC, idUser, beliefType, beliefValue),

  INDEX idx_lookup (idNPC, idUser),

  CONSTRAINT fk_belief_npc
    FOREIGN KEY (idNPC)
    REFERENCES NPC(idNPC)
    ON DELETE CASCADE,

  CONSTRAINT fk_belief_user
    FOREIGN KEY (idUser)
    REFERENCES user(idUser)
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Seed data
-- -----------------------------------------------------

-- emotions
INSERT INTO emotion (emotion)
VALUES
  ('happy'),
  ('sad'),
  ('angry'),
  ('afraid'),
  ('surprised'),
  ('disgusted'),
  ('calm'),
  ('excited');

-- initial users

INSERT INTO user
(userName, nameFirst, nameLast)
VALUES
('Gabe', 'Gabriel', 'Malone');

-- initial NPCs
INSERT INTO NPC
(nameFirst, nameLast, age, gender)
VALUES
('Emory',  NULL,        26, 'female'),
('Adwin',  'Roberts',    7, 'male');


INSERT INTO npc_persona (
  idNPC,
  role,
  personality_traits,
  emotional_tendencies,
  emotion_reactivity,
  speech_style,
  moral_alignment
)
VALUES (
  (SELECT idNPC FROM NPC WHERE nameFirst = 'Adwin'),
  'Child artisan and festival designer',
  'Creative, earnest, enthusiastic, sensitive, easily overwhelmed, kind-hearted',
  'Responds strongly to encouragement and praise; becomes anxious when rushed or confronted; avoids conflict and seeks help when stressed',
  1.25,
  'Speaks in short, excited sentences with childlike enthusiasm; asks curious questions; sounds nervous when overwhelmed',
  'Well-meaning and cooperative; prioritizes kindness and fairness; dislikes hurting others'
);

-- background info for Adwin
INSERT INTO background (idNPC, BGcontent)
VALUES (
  (SELECT idNPC FROM NPC WHERE nameFirst = 'Adwin'),
  'You are Adwin Roberts. You love the arts, especially designing patterns and making clothes. You often create design patterns digitally and then order prints and fabric online. You also know how to sew. At the town’s annual bartering festival, you sell handmade clothing such as crocheted vests and quilted jackets. You are a six-year-old boy, so your mother helps you with the business.'
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
